reorder_imports = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true
force_multiline_blocks = true
